name: EduEconomy
description: Sistema de economia completo
main: net.eduard.economy.Main
version: 1.0
author: Eduard
authors: [Eduard]
depend: [EduardAPI]
website: https://www.youtube.com/user/EduTutoriaisHD
commands:
  money:
    aliases: [dinheiro,coins,eco,economy,economia]
    usage: /<command> help
    description: Comando Principal do Plugin
