name: EduEconomy
description: Sistema de economia completo com suporte MySQ
main: net.eduard.economy.EduEconomy
version: ${project.version}
author: Eduard
authors: [Eduard]
depend: [EduardAPI]
website: https://www.youtube.com/user/EduTutoriaisHD
commands:
  money:
    aliases: [dinheiro]
    usage: /<command> help
    description: Comando Principal do Plugin
