name: EduEconomy
description: Sistema de economia completo com suporte MySQ
main: net.eduard.economy.EduEconomy
version: 1.0
author: Eduard
authors: [Eduard]
depend: [EduardAPI]
loadbefore: [ChestCommands,CommandNPC,VipZero,AtlasLoader]
website: https://www.youtube.com/user/EduTutoriaisHD
commands:
  money:
    aliases: [dinheiro]
    usage: /<command> help
    description: Comando Principal do Plugin
